eps_array = [
    {"name": "Nueva EPS", "codename": "nueva_eps"},
    {"name": "SURA", "codename": "sura"},
    {"name": "Sanitas", "codename": "sanitas"},
    {"name": "Coomeva", "codename": "coomeva"},
    {"name": "Compensar", "codename": "compensar"},
    {"name": "EPS Famisanar", "codename": "famisanar"},
    {"name": "Medimás", "codename": "medimas"},
    {"name": "Alianza Sanitas", "codename": "alianza_sanitas"},
    {"name": "Colpatria", "codename": "colpatria"},
    {"name": "Cafesalud", "codename": "cafesalud"},
    {"name": "EPS Sanitas", "codename": "sanitas_eps"},
    {"name": "Comfenalco", "codename": "comfenalco"},
    {"name": "Médico Coomeva", "codename": "medico_coomeva"},
    {"name": "Cruz Blanca", "codename": "cruz_blanca"},
    {"name": "Famisanar", "codename": "famisanar"},
    {"name": "Convida", "codename": "convida"},
    {"name": "Salud Total", "codename": "salud_total"},
    {"name": "EPS Inder", "codename": "eps_inder"},
    {"name": "Epsax", "codename": "epsax"},
    {"name": "Pijaosalud", "codename": "pijaosalud"},
    {"name": "Medimás EPS", "codename": "medimas_eps"},
    {"name": "EPS Sanitas", "codename": "eps_sanitas"},
    {"name": "Coosalud", "codename": "coosalud"},
    {"name": "Salud Vida", "codename": "salud_vida"},
    {"name": "EPS Mía", "codename": "eps_mia"},
    {"name": "Comfama", "codename": "comfama"},
    {"name": "Emssanar", "codename": "emssanar"},
    {"name": "Savia Salud", "codename": "savia_salud"},
    {"name": "Política Nacional de EPS", "codename": "politica_nacional_eps"},
    {"name": "Magisterio", "codename": "magisterio"},
    {"name": "Otra", "codename": "otra"},
]
