TREATMENTS_DATA = [
    {"name": "Neurología", "codename": "neurology"},
    {"name": "Neuropsicología", "codename": "neuropsychology"},
    {"name": "Neuropediatría", "codename": "neuropediatrics"},
    {"name": "Psiquiatría", "codename": "psychiatry"},
    {"name": "Medicina", "codename": "medicine"},
    {"name": "Nutrición", "codename": "nutrition"},
    {"name": "Cardiología", "codename": "cardiology"},
    {"name": "Endocrinología", "codename": "endocrinology"},
    {"name": "Oftalmología", "codename": "ophthalmology"},
    {"name": "Ginecología", "codename": "gynecology"},
    {"name": "Pediatría", "codename": "pediatrics"},
    {"name": "Dermatología", "codename": "dermatology"},
    {"name": "Oncología", "codename": "oncology"},
    {"name": "Otorrinolaringología", "codename": "otorhinolaryngology"},
    {"name": "Traumatología", "codename": "traumatology"},
    {"name": "Fisioterapia", "codename": "physiotherapy"},
    {"name": "Reumatología", "codename": "rheumatology"},
    {"name": "Neumología", "codename": "pulmonology"},
    {"name": "Urología", "codename": "urology"},
    {"name": "Anestesiología", "codename": "anesthesiology"},
    {"name": "Cirugía", "codename": "surgery"},
    {"name": "Odontología", "codename": "dentistry"},
    {"name": "Podiatría", "codename": "podiatry"},
    {"name": "Medicina Interna", "codename": "internal_medicine"},
]
