# Generated by Django 5.2.4 on 2025-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='codename',
            field=models.CharField(default=1, max_length=20, verbose_name='Codeame'),
            preserve_default=False,
        ),
    ]
